version: "3.8"

x-restart-policy: &restart-policy
  restart: always
x-default-env-file: &env-file
  env_file:
    - .env

services:
  tacn_db:
    <<: *restart-policy
    <<: *env-file
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - "./TACN_DB/DB/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - ./TACN_DB/DB/data:/var/lib/mysql
      - ./TACN_DB/DB/init:/docker-entrypoint-initdb.d
    networks:
      - mynet

  tacn_server:
    <<: *restart-policy
    <<: *env-file
    build: ./TACN_API
    depends_on:
      - tacn_db
    environment:
      - NODE_ENV=production
      - PORT=8700
      - WAIT_HOSTS=tacn_db:3306
      - DB_HOST=tacn_db
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - SECRET=${SECRET}
      - DB_NAME=tacn
    expose:
      - 8700
    ports:
      - 8700:8700
    volumes:
      - ./TACN_API/dist/uploads:/app/dist/uploads
    # links:
    #   - tacn_db
    networks:
      - mynet
    command: yarn start

  web_build:
    image: node:10-alpine
    container_name: tacn_web_build
    command: "sh -c 'yarn install && yarn build'"

    # command: "sh -c 'ls && yarn install && yarn start'"
    # ports:
    #   - 8338:3000

    volumes:
      - ./TACN_WEB:/app
    working_dir: /app
    networks:
      - mynet

  nginx:
    image: nginx:1.15.2-alpine
    container_name: tacn_nginx
    depends_on:
      - web_build
    volumes:
      - ./TACN_WEB/build:/var/www
      - ./TACN_WEB/nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - 3333:80
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
