
# FROM node:12-alpine as builder
# RUN mkdir -p /app
# WORKDIR /app
# # COPY package*.json /app/
# COPY ./ /app/
# RUN yarn 
# RUN yarn build


# FROM nginx:1.15.2-alpine
# COPY --from=builder /app/build /usr/share/nginx/html
# COPY --from=builder /app/nginx/default.conf /etc/nginx/nginx.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
